name: Deploy MkDocs

on:
  push:
    branches:
      - main  # or master, depending on your default branch
    paths:
      - 'resume_parser/documentation/**'  # Only trigger when docs change

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for proper versioning
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs-material
          pip install mkdocs-offline-plugin
          # Debug - list directory contents
          ls -la
          # Debug - show current directory
          pwd
      
      - name: Build documentation (for local testing)
        run: |
          # Check if directory exists
          if [ -d "resume_parser/documentation" ]; then
            echo "Directory exists"
            cd resume_parser/documentation
            # List contents to verify
            ls -la
            # Just build instead of deploying when testing locally
            mkdocs build
          else
            echo "Directory does not exist!"
            # List root directory to help debug
            ls -la
          fi
      
      # This step will be skipped in Act but will run on GitHub
      - name: Deploy documentation
        if: ${{ !env.ACT }}
        run: |
          cd resume_parser/documentation
          mkdocs gh-deploy --force 