name: Lint and Type Check

# Controls when the workflow will run
on:
  push: # Run on pushes to any branch
    branches: [ main ] # Adjust if your main branch has a different name
    paths:
      - 'app/**.py' # Only run if Python files in app/ change
      - '.github/workflows/lint.yml' # Run if the workflow itself changes
      - 'requirements.txt' # Run if dependencies change (adjust if needed)
  pull_request: # Run on pull requests targeting the main branch
    branches: [ main ] # Adjust if your main branch has a different name
    paths:
      - 'app/**.py'
      - '.github/workflows/lint.yml'
      - 'requirements.txt'

jobs:
  lint-and-type-check:
    runs-on: ubuntu-latest # Use the latest Ubuntu runner

    steps:
      # 1. Check out the repository code
      - name: Check out code
        uses: actions/checkout@v4

      # 2. Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' # Specify your project's Python version

      # 3. Install dependencies (including mypy and ruff)
      #    Assumes you have a requirements.txt file.
      #    If you manage dependencies differently (e.g., poetry, pdm),
      #    adjust this step accordingly.
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mypy ruff
          # If your project has its own dependencies needed for mypy, install them:
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          # Or for poetry: if [ -f pyproject.toml ]; then pip install poetry && poetry install --no-root; fi

      # 4. Run Ruff linter
      - name: Run Ruff
        run: ruff check app/

      # 5. Run Mypy type checker
      - name: Run Mypy
        run: mypy app/ 